language: node_js
cache:
  directories:
  - node_modules
  - src/bower
before_script:
- bower install
- gem install scss-lint
after_script:
- grunt mocha_istanbul && grunt coveralls
- grunt scsslint --force
- if [[ $TRAVIS_BRANCH == 'master' ]]; then ./.cf.sh review-ninja-staging; fi
- if [[ $TRAVIS_BRANCH == 'release' ]]; then ./.cf.sh review-ninja; fi